import Foundation

public enum XcircuiteFileFormat: String, Sendable, Hashable, Codable {
    case spice = "SPICE"
    case systemVerilog = "SYSTEM_VERILOG"
    case verilog = "VERILOG"
    case oasis = "OASIS"
    case gdsii = "GDSII"
    case lef = "LEF"
    case def = "DEF"
    case spef = "SPEF"
    case dspf = "DSPF"
    case liberty = "LIBERTY"
    case sdc = "SDC"
    case sdf = "SDF"
    case upf = "UPF"
    case cpf = "CPF"
    case vcd = "VCD"
    case fst = "FST"
    case stil = "STIL"
    case wgl = "WGL"
    case json = "JSON"
    case raw = "RAW"
    case csv = "CSV"
    case text = "TEXT"
    case unknown = "UNKNOWN"
}
